### ISSUE TITLE
Not adjusted to iframe enviorment

### ISSUE THREAD

**Issue by wojciech-skowronek** [pbakaus/viewporter#2]
Really cool library! Unfortunately it's not adjusted if game is embedded in iframe element. For example on Nexus S and iPhone zoom scale is a little bit to large, and some elements are not visible.

 Are you planning to support iframe environments?

**Comment by wojciech-skowronek** [comment]
also viewportchange is not calling if game is located in iframe

**Comment by pbakaus** [comment]
This should be fine now. Please reopen if still an issue.
