### ISSUE TITLE
Samsung Galaxy S - GT-I9000 - orientation change

### ISSUE THREAD

**Issue by fabriziogiordano** [pbakaus/viewporter#3]
Hi, on my Samsung Galaxy S orientation change is not fired properly.

**How to reproduce**
Open on.html in the demo folder in portrait mode, then turn in landscape mode.
The window height reported is 1270.

Open on.html in the demo folder in landscape mode.
The window height reported is 358 as expected.

This is the user agent string reported by the debug log:
user agent: Mozilla/5.0 (Linux; U; Android 2.3.3; it-it; GT-I9000 Build/GINGERBREAD) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1

**Comment by pbakaus** [comment]
Sorry for the late feedback - can you retry with the latest version of Viewporter and see if it is still an issue?

Thanks!
Paul

**Comment by fabriziogiordano** [comment]
Thank you Paul, I checked and now the values are corrects. Great!
