### ISSUE TITLE
Chrome for Android support

### ISSUE THREAD

**Issue by jzaefferer** [pbakaus/viewporter#6]
Opening a page with viewporter included on Chrome for Android causes an endless timer loop in prepareVisualViewport.

Background: Chrome for Android has a fixed header that can't be scrolled away. The IS_ANDROID checks for just 'Android' in `navigator.userAgent`, so detects the browser as Android and tries to scroll away the header, forever.

Workaround: Exclude 'CrMo' from the IS_ANDROID check:

`this.IS_ANDROID = /Android/.test(navigator.userAgent) && !/CrMo/.test(navigator.userAgent);`

**Comment by cookiengineer** [comment]
Thanks for the hint and the workaround!

I already commited and pushed the changes.
Problem and solution both verified with Google Galaxy Nexus S (ICSW Android).
