### ISSUE TITLE
jQuery Mobile compability

### ISSUE THREAD

**Issue by jzaefferer** [pbakaus/viewporter#8]
Currently viewporter seems to conflict with jQuery Mobile, resulting in a viewport bigger then intended. I could track it down to the resetActivePageHeight function in jquery.mobile.navigation.js, which was recently updated though: https://github.com/jquery/jquery-mobile/commit/84f1e4f257268b4b8d6132065263702e61074797

Would make sense to include a testpage in this project loading both jQuery Mobile, e.g. latest from code.jquery.com, and viewporter. I can help putting that together if there's interest.

In case someone is wondering why using both together: jQuery Mobile's custom events (tap, swipe) are very useful, trying to use that without the rest of the framework is not trivial.

**Comment by pbakaus** [comment]
Hey Jörn,

yeah, any help on putting that demo page together would be greatly appreciated. I'm happy to help with the actual viewporter implementation then. One question - doesn't jQuery mobile normalize the viewport already on its own?

Cheers,
Paul

**Comment by swernerx** [comment]
Waiting for further feedback...
