### ISSUE TITLE
Windows Phone 7.5 support

### ISSUE THREAD

**Issue by jzaefferer** [pbakaus/viewporter#9]
The IEMobile/9.0 browser is half-way decent, but then it doesn't support touch or orientationchange events and doesn't even trigger a resize event when the orientation actually changes.

I've got no idea how to support that sucker, but maybe someone else does and wants to chim in here.

**Comment by pbakaus** [comment]
Hey Jörn,

sounds like the only way to support it then is constant polling - unfortunately I don't have a device at hands to test this with right now, and it sounds rather bothersome to implement.

Cheers,
Paul

**Comment by jzaefferer** [comment]
Yeah, that sucks. Here's hoping they fix the orientationchange support or at least add a resize event.
